name: Lalit Patidar
description: Personal website
menu:
 - page: Home
   url: /home
 - page: Publications
   url: /publications
 - page: Research Projects
   url: /research
 - page: Curriculum Vitae
   url: /cv
menu_external:
 - title: Google Scholar
   url: "https://scholar.google.com/citations?user=_zm0ERIAAAAJ&hl=en"
 - title: Research Gate
   url: "https://www.researchgate.net/profile/Lalit_Patidar2"
 - title: LinkedIn
   url: "https://www.linkedin.com/in/lalit-patidar-9b82a02a/"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: LalitPatidar.github.io
locale: en_GB
