name: Lalit Patidar
description: Personal website
menu:
 - page: About
   url: /about
 - page: Papers
   url: /papers
 - page: Research Projects
   url: /research
   links:
    - title: "Project One"
      url: "#project-one"
    - title: "Project Two"
      url: "#project-two"
    - title: "Project Three"
      url: "#project-three"
    - title: "Project Four"
      url: "#project-four"
 - page: Curriculum Vitae
   url: /cv
   links:
    - title: Experience
      url: "#experience"
    - title: Education
      url: "#education"
    - title: Positions
      url: "#positions"
    - title: Miscellaneous
      url: "#miscellaneous"
 - page: Teaching
   url: /teaching
menu_external:
 - title: Google Scholar
   url: "https://scholar.google.com/citations?user=_zm0ERIAAAAJ&hl=en"
 - title: Research Gate
   url: "https://www.researchgate.net/profile/Lalit_Patidar2"
 - title: LinkedIn
   url: "https://www.linkedin.com/in/lalit-patidar-9b82a02a/"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: LalitPatidar.github.io
locale: en_GB
